### ISSUE TITLE
Trying to make an app, but it wont work

### ISSUE THREAD

**Issue by birbzunderscore** [kofigumbs/multi#103]
I'm running macOS 13.1 Ventura on my M1 Air.
I am trying to make an app for Pixlr Suite, but I find this issue each time:  _JSON Parse error: Expected '}'_
Here is my code:
{
  "tabs": [
    {
      "title": "Pixlr Suite" (expects '}' here)
      "url": "https://pixlr.com/suite"
      "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:108.0) Gecko/20100101 Firefox/108.0"
    },
  ],
  "windowed": true,
  "openNewWindowsWith": "com.mozilla.firefox"
}
A screenshot of the error below: ↓
<img width="921" alt="Screenshot" src="https://user-images.githubusercontent.com/108307819/210262618-3d636f4b-1970-4612-a50d-8d2251aa5ae3.png">

**Comment by kofigumbs** [comment]
It looks like your JSON is missing some commas, and thus incorrectly formatted. You can use a site like https://jsonlint.com to get more specific error messages.

**Comment by birbzunderscore** [comment]
@kofigumbs Thanks!
