### ISSUE TITLE
Unsupported browser version for Gmail

### ISSUE THREAD

**Issue by clinejj** [kofigumbs/multi#104]
When trying to use Gmail, Multi is apparently using an "unsupported browser" version and Gmail redirects to the old HTML style (the support article it links to is [here](https://support.google.com/mail/answer/6557?ctx=gmail#zippy=%2Cbrowser-isnt-supported)). I'm not sure what the user agent Multi reports is, but is it possible to update it?

**Comment by kofigumbs** [comment]
Yeah there’s a config for setting custom user-agents https://github.com/kofigumbs/multi/issues/89
