### ISSUE TITLE
Can Multi be a container for multiple web apps?

### ISSUE THREAD

**Issue by vurtomatic** [kofigumbs/multi#106]
Just discovered this app and I'm trying to set it up to replace all-in-one chat app like Ferdium.

If I currently have WhatsApp, Android SMS, Facebook Messenger, Discord, and Google Keep in one Ferdium, can I replicate this set up in Multi?

My first experiment with it has WhatsApp in one Multi container.

Sorry I looked through the examples folder and searched.

**Comment by kofigumbs** [comment]
Yes, you can have as many `tabs` as you want in your Multi app config. There’s an example of this [in the README](https://github.com/kofigumbs/multi#json-configuration) near the paragraph that says “Here's a fancier example”. 

And if you do make an all-in-one chat app that you like, I’d love to accept a contribution to the Examples directory.
