### ISSUE TITLE
Dark Mode JS or CSS 

### ISSUE THREAD

**Issue by Genxster1998** [kofigumbs/multi#108]
Any way to make sites dark with static css or js ?
IF there is , please suggest ...

**Comment by vurtomatic** [comment]
I'm trying to figure that out too.

WhatsApp, Google Messages, Discord, and Google Keep is automatically in dark mode.

But Facebook Messenger (messenger.com) is in light mode.

In Ferdium, there's a setting "Appearance > Enable Dark Mode" that seems to tell the web apps the browser or system is in dark mode. I don't recall doing anything to get Facebook Messenger in dark mode.

**Comment by kofigumbs** [comment]
You can use the [Custom CSS](https://github.com/kofigumbs/multi#custom-jscss) feature to create your own dark mode. Some sites make it easier than others, but there are many example stylesheets online that you can use as a starting point. For instance, Ferdium makes its dark mode styles available online—here are their [overrides for LinkedIn dark mode](https://github.com/ferdium/ferdium-recipes/blob/fc12cd18b9a2b0d47322e77ced4d7e8e5de02456/recipes/linkedin/darkmode.css). I'd recommend trying to find dark mode CSS stylesheets for whatever site you use in Multi.
