### ISSUE TITLE
Cannot access local network/localhost  

### ISSUE THREAD

**Issue by Rastafabisch** [kofigumbs/multi#110]
I'm trying to run [Hyperion Remote](http://gamadril.github.io/hyperion-remote) using Multi.
While it runs fine it cannot control anything, spitting out a websocket error. (It does work fine from Safari using the same settings.)
 <img width="275" alt="Bildschirm­foto 2023-02-19 um 13 30 20" src="https://user-images.githubusercontent.com/38974866/219949193-a0be7afd-4e13-4b8b-ada2-5e70377f87fa.png">
This can be tested by installing [Hyperion](https://github.com/hyperion-project/hyperion.ng/releases) (does not need to be setup for this to work). What does work however is directly accessing the domain and port as a multi web app.

**Comment by kofigumbs** [comment]
Localhost access works generally, so this could be an issue specific to Hyperion. If you'd like to dig in further, I'd recommend looking at the console for a more specific error (right click anywhere, select "Inspect Element", and then look in the "Console" tab). I'll leave this issue open in case you want to use it to try and find other folks using Hyperion.

**Comment by Rastafabisch** [comment]
<img width="1068" alt="Bildschirm­foto 2023-02-20 um 20 35 20" src="https://user-images.githubusercontent.com/38974866/220186490-791438ba-1102-4055-8f7c-a7a8b497bd0b.png">

This is what I get. I don't know what to do about it however.

**Comment by kofigumbs** [comment]
It looks like your on a "https" (secure) URL, but the WebSocket is using "ws" (insecure). These have to match. Since this app seems designed to work with localhost, maybe you could try changing your URL to use the insecure version, "http" instead of "https".
