### ISSUE TITLE
Migrate from NotificationCenter to UserNotifications

### ISSUE THREAD

**Issue by kofigumbs** [kofigumbs/multi#112]
I'm trying to troubleshoot because I'm experiencing the same thing, no notifications from whatsapp.

I tried using alerts and banners, also have `alwaysNotify` set to true.

When I enable "Show in Notification Center", I see a stack of old notifications from a day and more ago but not the latest ones when I text myself on whatsapp.

At some point, Multi at least had notifications in the Notification Center but never showed any banner notifications. And then it stopped showing notifications in Notification Center and banners completely.

After rebooting the laptop, I saw a banner notification from whatsapp once. Subsequently I can hear a notification sound but not visible notification. Notification Center is showing the notifications though.

_Originally posted by @vurtomatic in https://github.com/kofigumbs/multi/issues/86#issuecomment-1445393109_

**Comment by kofigumbs** [comment]
@vurtomatic I moved your comment to a new issue to avoid notifying other users. Do you have notification problems in other Multi apps other than WhatsApp? Could you try testing with https://www.bennish.net/web-notifications.html, which should help you identify whether this is a WhatsApp issue or a Multi issue?

**Comment by vurtomatic** [comment]
Thank you for cleaning up and organizing the discussion @kofigumbs .

I tested the link by opening it up in Safari, I received notifications normally.

I tried a bit of trial and error and I _think_ when I have old Multi notifications in Notification Center, the new/current notification banners stop appearing.

After clearing the old notifications from Notification Center, notification banners appear again.

I don't know if old notifications in Notification Center is actually preventing banners from appearing (other apps don't seem to have the exact same problem), but it's the only change I made (clearing old notifications from Notification Center) that's seems to bring the Multi notification banners back.

**Comment by vurtomatic** [comment]
I'm noticing the same behavior with SMS notifications.

**Comment by kofigumbs** [comment]
I still haven't been able to exactly reproduce your issue using a publicly accessible website—please let me know if you make any progress on that front. My latest theory is that WhatsApp is using the `Notifications.renotify` property, which isn't implemented in Multi.

I think this issue is sufficient motivation to migrate notifications to use non-deprecated APIs though. That should make any future debugging easier and more consistent with the latest online resources. I updated the issue title to reflect that.
