### ISSUE TITLE
Multi app not respecting top-level config

### ISSUE THREAD

**Issue by popscallion** [kofigumbs/multi#113]
I'm running into some unexpected behavior with Multi, specifically with the top-level configuration options. Neither keepOpenAfterWindowClosed nor alwaysOnTop are behaving as expected. I'm running Ventura 13.2.1 with no other window managers active. Config file to reproduce:

`{
  "tabs": [
    {
      "title": "Instagram",
      "url": "https://www.instagram.com/direct/t/",
      "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6 Safari/605.1.15"
    }
  ],
  "keepOpenAfterWindowClosed": true
}`

**Comment by kofigumbs** [comment]
Hello! Those two options were just added in the latest version, 2.2.3. Can you confirm which version of Multi you're using? I just ran a quick test with the config you provided, and `keepOpenAfterWindowClosed` seems to work as expected.

**Comment by popscallion** [comment]
Ah that was it—updated to 2.2.3 and everything is working as expected! Thank you!
