### ISSUE TITLE
can open new tab when click dock icon if it‘s all tab is closed.

### ISSUE THREAD

**Issue by touchmii** [kofigumbs/multi#114]
{
  "tabs": [
    {
      "title": "Slack",
      "url": "https://app.slack.com/client/",
      "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6 Safari/605.1.15"
    }
  ],
  "windowed": true,
  "keepOpenAfterWindowClosed": true,
  "alwaysNotify": true,
  "alwaysOnTop": false,
  "openNewWindowsWith": "com.apple.Safari",
  "openNewWindowsInBackground": true
}

I use those config, when I close windows app don't quit, but click dock app icon can‘t new tab.

**Comment by kofigumbs** [comment]
Implemented in [v3.0.0](https://github.com/kofigumbs/multi/releases/tag/v3.0.0)
