### ISSUE TITLE
No notifications for Instagram, WhatsApp or Facebook Messenger

### ISSUE THREAD

**Issue by muzidube** [kofigumbs/multi#115]
If I create a tab for "https://www.bennish.net/web-notifications.html" and test the notifications that way, they work perfectly. I get alert notifications and clicking the notification takes me to the app. However, for Instagram DMs, WhatsApp messages and Facebook Messenger messages I get no notifications.

I have checked the settings for the app and enabled all notifications for it. Also, I have noticed that Instagram does not refresh sometimes and I will have to force a refresh to get newest messages to appear.

My json is below:

{
  "tabs": [
    {
      "title": "Instagram",
      "url": "https://www.instagram.com/direct/inbox/",
      "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6 Safari/605.1.15"
    },
    {
      "title": "WhatsApp",
      "url": "https://web.whatsapp.com/",
      "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6 Safari/605.1.15"
    },
    {
      "title": "Messenger",
      "url": "https://www.messenger.com/t/100000299233401/",
      "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6 Safari/605.1.15"
    }
  ],
  "alwaysNotify": true
}

**Comment by kofigumbs** [comment]
Notifications were revamped in [v3.0.0](https://github.com/kofigumbs/multi/releases/tag/v3.0.0)—could you confirm whether the issue persists if you recreate your app under the new version?

- Download/install the new release
- Recreate the app, by opening it's Preferences and hitting save (or by running `create-mac-app` as described in the README)
