### ISSUE TITLE
Find in page feature

### ISSUE THREAD

**Issue by forrestnash** [kofigumbs/multi#12]
I was hoping to use Multi to wrap our backend software, and it's almost perfect for us. But the inability to use Command + F to find text within the page is necessary for us to do our work quickly. It would be great if this was added at some point if you have time.

**Comment by hkgumbs** [comment]
That's neat to hear you're considering Multi for work! Implementing `Cmd-F` seems like a natural improvement—I'll let you know when I get it implemented.

**Comment by kofigumbs** [comment]
Here's the custom JS to implement Cmd-F: https://gist.github.com/kofigumbs/a966f381cd08ec27addf2b4e7e3246bc. You can add it to your Multi app with a config that looks something like this:

```json
{
  "tabs": [
    {
      "title": "My App",
      "url": "https://example.com",
      "customJs": [
        "https://gist.githubusercontent.com/kofigumbs/a966f381cd08ec27addf2b4e7e3246bc/raw/9f3ef69314272a25b1db8c5080483dbfed61a080/find.js"
      ]
    }
  ]
}
```

It's a bit ugly and hacked together, so feel free to modify for something that works better for you. I'm also planning a "config editor" feature, to make finding/sharing these kinds of snippets a bit easier.
