### ISSUE TITLE
Support for macOS 11.x

### ISSUE THREAD

**Issue by voltechs** [kofigumbs/multi#124]
Ok... I'm officially going insane. Not sure what changed, as the binary in the release on GitHub hasn't been updated since two weeks ago, but suddenly I'm unable to open Multi.app on my mac running Big Sur, even though no more than a few days ago I was creating apps and running them just fine. In fact I still have a few Multi apps that still run...

I _did_ do a `brew update/upgrade` recently, and for some reason I saw some update about `Multi.app` but I never installed it via brew, I had downloaded it right from GitHub...

Not really sure what's going on. Did something change with Multi? I could have sworn I'd been using 3.0.0 this whole time.

**Comment by danieltomasz** [comment]
@voltechs `brew info multi` will tell you if you installed formula via brew

**Comment by voltechs** [comment]
Strange, I could have sworn I downloaded 3.0 on macOS 11 and it was working fine, but I'll give 2.4 a try. Thanks!
