### ISSUE TITLE
Icon doesn't show in the dock

### ISSUE THREAD

**Issue by retorquere** [kofigumbs/multi#131]
The icon shows in the Finder, the app switcher and in spotlight, but in the dock it looks like this:

![image](https://github.com/kofigumbs/multi/assets/132108/02d9a62f-40f1-4516-ae15-1552b4751092)

**Comment by kenttech** [comment]
I have the same issue.  The first app I created worked fine.  All apps created since have the same blank icon in Finder.  Anyone have any insight?

**Comment by kenttech** [comment]
Actually just looks like some apps have the blank icon.  Haven't been able to make any rhyme or reason of it.

**Comment by retorquere** [comment]
If I can't distinguish between running apps, this kind of defeats the point of multi for me.
