### ISSUE TITLE
A small problem... 

### ISSUE THREAD

**Issue by ulrichloose** [kofigumbs/multi#141]
I would like to make the website https://falstad.com/circuit/circuitjs.html to a web app. This also works very well... The problem is - if you want to save a simulation locally (CMD S), you will be asked for the file name, but no file is written, but the file content is displayed as text in the window. With Safari in Sonoma, on the other hand, the opening of an simulation does not work.

Is it possible to fix the problem?

**Comment by kofigumbs** [comment]
Multi doesn't support native file downloads yet, and the current behavior shows what would have been downloaded in the browser window. I linked this to the tracking issue for that feature, if you'd like to follow it or take a stab at contributing.
