### ISSUE TITLE
Tab Bar

### ISSUE THREAD

**Issue by greggh** [kofigumbs/multi#23]
I would like a tab bar at the top. I actually like showing the tabs and clicking on them. Is this possible?

**Comment by hkgumbs** [comment]
It's possible, and I almost included it in 2.0, but in the end I reduced scope and skipped it. I'll leave this issue open and update when I get to it 👍🏾

**Comment by kofigumbs** [comment]
This is released in [2.1.0](https://github.com/kofigumbs/multi/releases/tag/v2.1.0).
