### ISSUE TITLE
Notifications broken in 2.0.7

### ISSUE THREAD

**Issue by kofigumbs** [kofigumbs/multi#39]
I am not receiving banner notifications on slack.
... I am on MacOS Catalina 10.15.6

_Originally posted by @makeavish in https://github.com/kofigumbs/multi/issues/26#issuecomment-706705338_

**Comment by kofigumbs** [comment]
This broke in a recent release. Committing a fix now and will batch with the next release in the next day or two.

**Comment by kofigumbs** [comment]
@ericboehs I'm pulling your comment into this issue.

I'm also not getting notifications on 10.15.7 (Safari 14.0). I tried the web-notifications.html app and nothing happens. If I click Authorize button it says permission is granted but I can't get it to notify me even if I do "Show me in 5s" and then de-focus the app.

_Originally posted by @ericboehs in https://github.com/kofigumbs/multi/issues/14#issuecomment-706759773_

**Comment by ericboehs** [comment]
Excellent. I look forward to the release.

**Comment by kofigumbs** [comment]
This is released in https://github.com/hkgumbs/multi/releases/tag/v2.0.8

**Comment by ericboehs** [comment]
I've downloaded 2.0.8 and I'm happy to report it's working! Yay! Thanks @kofigumbs.

**Comment by makeavish** [comment]
@kofigumbs Thanks for release.
Now I can see notifications in notification side bar and also hear notification but I still can't see banner.
I have enabled permission for banner alerts for multi app named "slack test".
Attaching pictures for more details.
![Screenshot 2020-10-14 at 10 50 42 PM](https://user-images.githubusercontent.com/9512100/96024042-e1a8e380-0e70-11eb-903f-cde49554de20.png)
![Screenshot 2020-10-14 at 11 01 45 PM](https://user-images.githubusercontent.com/9512100/96024357-3d736c80-0e71-11eb-90f7-29aa89fabd6d.png)

**Comment by kofigumbs** [comment]
@makeavish That's strange! I think that if there's an entry in the Notification Center, that means that the system did attempt to deliver the banner notification and that something else prevented it. But I can't think of a case where you'd still be hearing the sound. I also created a Slack test app myself with 2.0.8, and I do see a notification when I use `/remind me to test in 1 minute`.

Could you take the following steps to help us narrow down the problem:

 - Create a new app with the following config:
   ```
     {"tabs":[{"title":"Test","url":"https://www.bennish.net/web-notifications.html"}]}
   ```
   When you open the app, try clicking the "Show in 5s" button and putting the app in the background.
   You may not see a notification the first time (since Multi needs to get Notification permissions for each new app),
   but if you do it again, the notification should appear.
 - In *System Preferences > Notifications > Do Not Disturb* verify that make no other setting is preventing the banners.

**Comment by makeavish** [comment]
![Screenshot 2020-10-16 at 4 02 58 PM](https://user-images.githubusercontent.com/9512100/96248352-12039580-0fc9-11eb-9080-87fbf1f229b0.png)
I am facing same issue, but this time I can even hear the notification.
Notification is in queued stage as we can see.
![Screenshot 2020-10-16 at 4 05 14 PM](https://user-images.githubusercontent.com/9512100/96248586-6444b680-0fc9-11eb-8328-6c82a368dfbf.png)

**Comment by kofigumbs** [comment]
@makeavish Do you see banner notifications for other apps? To test, you can go to [the notification test site] in Safari, and click "Authorize", click "Show in 5s", and then put Safari in the background.

Also, did you verify the settings in *System Preferences > Notifications > Do Not Disturb*?

**Comment by makeavish** [comment]
@kofigumbs Yes I can see banner in safari as well as firefox (even in minimized state). I have also verified Do Not Disturb.
