### ISSUE TITLE
Javascript Injection

### ISSUE THREAD

**Issue by dternyak** [kofigumbs/multi#40]
Support javascript injection onload for additional customization.

The use case I have is to add content security policy to gmail in order to prevent it from loading new emails throughout the day, and only retrieve them at certain hours (to prevent gmail addiction).

**Comment by kofigumbs** [comment]
Someone requested this in #32, and I just haven't gotten to it yet. I'm going to close this issue since it's already tracked there. If you subscribe to that one you'll get notified when I close it.

(My response time here is probably an indicator that I have a GMail addiction myself 😅)

**Comment by dternyak** [comment]
Perfect!

> (My response time here is probably an indicator that I have a GMail addiction myself 😅)

Ha! I hope you prioritize it then ;)
