### ISSUE TITLE
Custom JS

### ISSUE THREAD

**Issue by karbassi** [kofigumbs/multi#41]
@kofigumbs Could you share a full example of an app with the customJs feature?

I can't get any code to run.

Also, if your example you have `console.log`. How do I launch the console/dev tools in the app?

**Comment by kofigumbs** [comment]
The dev tools are [disabled in production](https://github.com/kofigumbs/multi/blob/2.x/Sources/Shared/WKWebView+enableDevelop.swift#L5), so I suppose `console.log` is a poor example for that reason. Although, now that folks might need to debug customJs in Multi, I think I should just enable dev tools all the time.

Here's a full example with some custom JS (`setTimeout(() => alert('Hi'), 5000)`) using the URL-encoding method:

```json
{
  "tabs": [
    {
      "title": "Slack Lite",
      "url": "https://app.slack.com/client",
      "customJs": [
        "data:,setTimeout%28%28%29%20%3D%3E%20alert%28%27Hi%27%29%2C%205000%29"
      ]
    }
  ]
}
```

**Comment by kofigumbs** [comment]
Gonna resolve this—please let me know if you have any more questions though
