### ISSUE TITLE
Unable to download a file

### ISSUE THREAD

**Issue by droath** [kofigumbs/multi#43]
I've created an multi application for basecamp, but I'm unable to download files within the the application. Is that something that can be supported?

**Comment by kofigumbs** [comment]
Hey @droath, thanks for trying Multi and creating these issues!

I just created Basecamp app to try this out, and when I go into "Docs & Files", select a file, and click "Download" then Multi opens the download link in my browser. If I'm already signed into Basecamp in that browser, then the file downloads immediately. That's the expected flow for file downloads in Multi right now. (You can change which browser is the Multi default with the [JSON config](https://github.com/kofigumbs/multi/#json-configuration).)

Does that clear things up for you? Or were you trying to download files a different way?

**Comment by droath** [comment]
@kofigumbs, no problem, I really like what you've done with Multi! I've been using the app to solve multiple use cases.

I guess I was expecting it to open a download dialog within the Basecamp application, that was created using Multi. I can change the config to open in the browser, but I'll have to sign in again. Which is fine, as I don't download a lot. 

Thanks for the quick response and the work you've put into this app. Much appreciated!

**Comment by kofigumbs** [comment]
Yea, that's a reasonable expectation 😅. Good news is that for Basecamp you should only have to sign in on the first download. And if you want to use a different browser than your system default, you can configure that in Multi with `openNewWindowsWith`.
