### ISSUE TITLE
Slack doesn't auto-update in Multi

### ISSUE THREAD

**Issue by neilio** [kofigumbs/multi#49]
Hi-ho -

I have an instance of Slak running in Multi and realized today that it's not auto-updating when new messages come; I need to explcitly reload the screen to see new messages.

Not sure what kind of troubleshooting or logs would help you. Let me know if I can help narrow this down!

**Comment by kofigumbs** [comment]
Hey Neil! I haven't noticed this with my Slack Multi app, so I'll definitely need more information... just not sure what exactly to ask. The config you shared last week included a GMail tab—does that one auto reload?

**Comment by neilio** [comment]
Yep, Gmail auto updates. It's very odd - I get a Slack message that the last update was X minutes ago and an option to load new messages. I only get new messages when I hit that link or command+r.

**Comment by kofigumbs** [comment]
Unfortunately, this is either an issue with WebKit (Apple's system library) or with Slack, so I can only provide band-aids and not proper fixes. Here's some Custom JS that will check your window every 90 seconds for the text "load new messages" and if it appears, reload your tab:

```js
setInterval(() => {
  if (document.body.innerText.includes('Load new messages.'))
    window.location.reload();
}, 90000)
```

Sorry if that's an underwhelming solution, but hopefully it gets you unblocked. Here's why I think it might be a WebKit bug: this issue tracker link shows other folks having this same problem in the last couple months: https://bugs.webkit.org/show_bug.cgi?id=149551

I have no idea how WebKit updates are distributed. The bottom of that conversation suggests it's closed, but I'm not sure if that means that that's the code running on your Mac. On the other side of things, Slack's website has specific documentation about this issue, where they suggest you enable net logs and content their support team: https://slack.com/help/articles/205138367-Troubleshoot-connection-issues#websocket-trouble

**Comment by neilio** [comment]
Thanks foe the code snippet. I'd give it a whirl, except I'm on holidays now and there's no darn way I'm jumping into slack 😄.

I'm not sure why this works in other WebKit-based single site apps. I wonder if it's specifically an Apple Silicon bug? When I'm back at work I'll launch the Multi app in Intel and see what happens.
