### ISSUE TITLE
Allow drag and drop URLs

### ISSUE THREAD

**Issue by chrismessina** [kofigumbs/multi#50]
I would like to use Multi for Substack Reader, but to authenticate, Substack sends me an email with a link that use to login. I can't seem to open this URL within the Multi app that I created. 

If I could drag and drop the URL that I received in my email, I could authenticate successfully.

**Comment by kofigumbs** [comment]
Hey Chris, thanks for checking out Multi! And tweeting about it!!

Taking a closer look at this, I realized it could be solved with the `customJs` feature. [Here's a Gist](https://gist.github.com/kofigumbs/b5f393f4e05160d7764336a851dd8a6d) that adds a "URL bar" that opens with `⌘K`. Here's an updated config based on what you posted in #51:

```js
{
  "tabs": [
    {
      "title": "Substack Reader",
      "url": "https://reader.substack.com",
      "customJs": ["https://gist.githubusercontent.com/kofigumbs/b5f393f4e05160d7764336a851dd8a6d/raw/f72f191466519624c26afcd0bdc7374fcf7e1924/url.js"]
    }
  ]
}
```

Sounds like you only need this functionality to login, so you could even get rid of the `customJs` field after that. In case it conflicts with some Substack Reader shortcut.

Does that work for you? If so, I'll clean up the JS and add it to the [Custom JS showcase](https://github.com/kofigumbs/multi/blob/2.x/Documentation/CUSTOM-JS.md#examples).

**Comment by chrismessina** [comment]
Ah nice. Fortunately I was able to sign in with my password in the meantime — but since many services are moving to sign in via emailed link, I wonder if making this drag and drop capability available generally would be useful?

**Comment by kofigumbs** [comment]
Ok, so I should have just looked into drag/drop originally like you suggested 😅 . Definitely sounded harder than it ended up being—there's a super easy way to enable this with Custom JS: `document.addEventListener("dragover", e => e.preventDefault())`. Here's the full updated JSON:

```json
{
  "tabs": [
    {
      "title": "Substack Reader",
      "url": "https://reader.substack.com",
      "customJs": ["data:,document.addEventListener%28%22dragover%22%2C%20e%20%3D%3E%20e.preventDefault%28%29%29"]
    }
  ]
}
```

I prefer implementing as many features as possible with custom CSS/JS, hence my last two responses. I'm also planning a "config editor" feature, where this is all made easier.
