### ISSUE TITLE
Sidebar Icons on Apps Not Shown Correctly

### ISSUE THREAD

**Issue by agungsijawir** [kofigumbs/multi#53]
Found a weird on creating Discord instance. Server icon on discord not shown correctly as shown in the picture below:
![Screen Shot 2020-12-27 at 9 30 49 PM](https://user-images.githubusercontent.com/1901132/103173055-d0298200-488a-11eb-9666-01bdc98a68d6.png)

Following config used to create the instance:
```
{
  "tabs": [
    {
      "title": "Discord Lite",
      "url": "https://discord.com/login"
    }
  ]
}
```

Apps: Version 2.0.8
Safari Version: 13.1.1

**Comment by kofigumbs** [comment]
I just tried creating a Discord app, and I'm not seeing the same issue. I have seen this before though, when using Discord in Chrome. It generally resolves itself though 🤷🏾‍♂️.. I don't think this is Multi-specific, so the normal stuff — re-logging in, restarting the app, rebooting your computer — is probably your best bet. Some folks even have success just refreshing the page (which is Cmd-R in Multi): https://support.discord.com/hc/en-us/community/posts/360058063652-Can-t-see-any-server-icon.

**Comment by agungsijawir** [comment]
Ok, I will try and update to you asap!
