### ISSUE TITLE
clicking to download a PDF reliably crashes multi

### ISSUE THREAD

**Issue by llimllib** [kofigumbs/multi#60]
In fastmail, with the most recent Multi, clicking to download a PDF of a donation receipt causes my fastmail Multi window to go to a white screen and become unresponsive.

https://user-images.githubusercontent.com/7150/104929126-7e4bb780-5971-11eb-97dc-5c76b005c211.mov

I'd be happy to help debug it if the cause is unknown, it's easy to reproduce.

**Comment by kofigumbs** [comment]
I haven't implemented native file downloading in Multi yet. So far, I've been encouraging people to let their default browser handle that. Here's a quick `customJs` script to tell the Fastmail download pages to open in your browser:

```js
if (window.location.href.startsWith("https://www.fastmailusercontent.com/jmap/download")) {
  open(window.location.href);
  window.history.back();
}
```

I tested it with this config:

```json
{
  "tabs": [
    {
      "title": "Fastmail",
      "url": "https://fastmail.com",
      "customJs": [
        "data:,if%20%28window.location.href.startsWith%28%22https%3A%2F%2Fwww.fastmailusercontent.com%2Fjmap%2Fdownload%22%29%29%20%7B%0A%20%20open%28window.location.href%29%3B%0A%20%20window.history.back%28%29%3B%0A%7D"
      ]
    }
  ]
}
```

I'll track native file downloads in another issue.

**Comment by kofigumbs** [comment]
Oh also, Multi didn't crash in my tests: it's seemed that Fastmail just served a blank page on its download paths. I was always be able to navigate back with `Cmd-[`.
