### ISSUE TITLE
Tabs / keyboard shortcuts mismatched

### ISSUE THREAD

**Issue by neilio** [kofigumbs/multi#61]
Have a reproducible issue here that's two parts but related:

Config is set up with these services declared in this order:

1. Slack
2. Gmail
3. Miro
4. Jira

When Multi launches it always loads the tabs in the window in this order:

1. Slack   |     4. Jira   |    3. Miro   |    2. Gmail  

But the command + # keyboard shortcuts match the order defined in the config:

command + 1 = Slack
command + 2 = Gmail
etc.

**Comment by msanders** [comment]
I'm seeing this as well after disabling the `windowed` option. The tabs can be dragged to re-order but it doesn't persist across launches.

**Comment by msanders** [comment]
I'm seeing this as well after disabling the `windowed` option. The tabs can be dragged to reorder but it doesn't persist across launches.

**Comment by kofigumbs** [comment]
This is released in https://github.com/kofigumbs/multi/releases/tag/v2.1.2
