### ISSUE TITLE
AdGuard (and ad blockers generally) don't work in multi

### ISSUE THREAD

**Issue by llimllib** [kofigumbs/multi#62]
I had the bright idea to create a youtube multi app, but youtube with ads is so painful that there's no way I can use it.

I'm not certain if this is possible to fix.

**Comment by pkrayzy** [comment]
One solution is to use the Automatic Proxy mode in Adguard instead of the Network Extension. Another option (and one I've had really spotty success with) is editing the blocklist.json file to use Adguard's rules converted into a WebKit friendly format.

**Comment by kofigumbs** [comment]
I think @pkrayzy's suggestion for the Adguard rules is the way to go for this one. I'm not going to be able to support ad-blocking on every website, I'd be open to adding a `customBlocklist` field to the config if that would work for y'all. That way you could maintain your own AdGuard bindings separate from the ones Multi ships with.

**Comment by avichou** [comment]
> One solution is to use the Automatic Proxy mode in Adguard instead of the Network Extension. Another option (and one I've had really spotty success with) is editing the blocklist.json file to use Adguard's rules converted into a WebKit friendly format.

I hope this isn't too dumb of a question, but could u kindly point me in the direction of editing the files ?
im kinda lost tbh lol,my only wish is to block ads in a YouTube music pwa

**Comment by avichou** [comment]
> I think @pkrayzy's suggestion for the Adguard rules is the way to go for this one. I'm not going to be able to support ad-blocking on every website, I'd be open to adding a `customBlocklist` field to the config if that would work for y'all. That way you could maintain your own AdGuard bindings separate from the ones Multi ships with.

any news on the custom blocklist field?

**Comment by avichou** [comment]
> I had the bright idea to create a youtube multi app, but youtube with ads is so painful that there's no way I can use it.
> 
> I'm not certain if this is possible to fix.

im literally replying to everyone at this point lol,but have u managed to fix it?removing ads from YouTube (music in my case) is the only thing I need to move out from chrome/electron pwa

**Comment by kofigumbs** [comment]
@avichou the blocklist is distributed within the app bundle: `Multi.app/Contents/Resources/blocklist.json`. See the WebKit documentation for more details about block rules and their syntax: https://webkit.org/blog/3476/content-blockers-first-look/

There is still no per-app blocklist, which is why this issue is still open.

**Comment by pkrayzy** [comment]
I think have found a way to make this work. 

If you use the Adguard script below from the iOS shortcut in the CustomJS, I have had good success in limiting ads:
 
{
  "tabs": [
    {
      "title": "YouTube",
      "url": "https://youtube.com/",
      "customJs": [ "https://raw.githubusercontent.com/AdguardTeam/BlockYouTubeAdsShortcut/master/index.js" ]
    }
  ]
}

**Comment by llimllib** [comment]
clever!

**Comment by llimllib** [comment]
I've used that for 5 minutes now and so far it's worked perfectly, thank you

**Comment by kofigumbs** [comment]
This is awesome -- thanks for sharing @pkrayzy!!

**Comment by pkrayzy** [comment]
Forget me man - thanks @kofigumbs for making a really awesome and useful tool!

**Comment by tristan-k** [comment]
Anyone got fullscreen support working in Youtube? I'm unable to hit the fullscreen button in the youtube player. It's says the browser doesnt support fullscreen.

**Comment by llimllib** [comment]
This just stopped working for me, no idea why. The file is still up

**Comment by kofigumbs** [comment]
The better.fyi blocklist was removed in [v3.0.0](https://github.com/kofigumbs/multi/releases/tag/v3.0.0), so I don't think it makes sense to leave this issue open. I'd recommend using Custom JS to block ads, like in the workaround mentioned above.
