### ISSUE TITLE
I cant build the package

### ISSUE THREAD

**Issue by vlashada** [kofigumbs/multi#63]
Hi!

I was wanting to contribute to this project, so I downloaded the project and opened it in Xcode. Then I try running through runtime/my mac or Preferences/my mac, I get this error: "Multi.app is missing essential files — try re-installing it."

I think the problem is that "Multi.app" is not part of the bundle. Do anyone know how to fix this?

**Comment by kofigumbs** [comment]
Hey, thanks for your interest in contributing. I don't use XCode to develop Multi, so I don't know what it would take to get it working there. I build the project by running `make` from the command line, which fills in the missing bits of the Multi.app bundle.

**Comment by kofigumbs** [comment]
Let me know if I can help in any other way.
