### ISSUE TITLE
The application "%@" is not open anymore

### ISSUE THREAD

**Issue by llimllib** [kofigumbs/multi#71]
when I click on any link right now, I'm getting this error:

<img width="420" alt="image" src="https://user-images.githubusercontent.com/7150/121075611-6602fa80-c7a3-11eb-9d07-6989dfbdd444.png">

I did in this session switch my default browser from Firefox to Safari, but restarting my Multi app (and upgrading to multi 2.1.3) have not helped the situation.

**Comment by kofigumbs** [comment]
Could you provide your macOS version as well? Thanks

**Comment by llimllib** [comment]
That computer is still on Catalina (company requirements), sorry I should have included that in the report

**Comment by llimllib** [comment]
closing due to not enough info to fix
