### ISSUE TITLE
Error 10827 on create new app

### ISSUE THREAD

**Issue by Alkapims** [kofigumbs/multi#72]
Cannot open new Multi app:
<img width="794" alt="Capture d’écran 2021-06-07 à 23 28 39" src="https://user-images.githubusercontent.com/68518871/121089976-30cccb80-c7e8-11eb-8528-649ab55c3f54.png">

Version:
<img width="952" alt="Capture d’écran 2021-06-07 à 23 31 08" src="https://user-images.githubusercontent.com/68518871/121090196-8012fc00-c7e8-11eb-82d9-612e52745035.png">

MacOS Big Sur 11.4

**Comment by kofigumbs** [comment]
It looks like you might not have installed Multi and are instead trying to run it directly from the `.dmg` file. You'll want to make sure you installed Multi first (by dragging the Multi app icon into your Applications directory) and then running the copy of Multi that lives in your Applications directory.

Please let me know if that works for you. And thanks for trying Multi!
