### ISSUE TITLE
Support for Splash Screen (Image or Video or Both) 

### ISSUE THREAD

**Issue by Dev-ManishTomar** [kofigumbs/multi#74]
The White background feels very Jarring whenever the app loads for the first time, If splash screen support is added then it will make it a more pleasing experience.

**Comment by kofigumbs** [comment]
Forgot to update after [our Twitter conversation](https://twitter.com/kofigumbs/status/1485744725248421897). If anyone reading has time/interest in contributing, I'd suggest starting by looking into how Tauri and/or Electron do it. Happy to discuss implementation ideas here.

**Comment by kofigumbs** [comment]
As of [v3.0.0](https://github.com/kofigumbs/multi/releases/tag/v3.0.0), you can use Custom JS/CSS to implement this. Specifically since custom scripts run at document load time, you have a lot more flexibility on the initial load experience.
