### ISSUE TITLE
_blank link

### ISSUE THREAD

**Issue by vanyauhalin** [kofigumbs/multi#78]
For me, Multi are a great way (<3) to separate work tabs. Sometimes I have to open `<a target="_blank" />`, but they open in the default browser. I think it would be great to open these links in a new tab within the multi itself.

**Comment by kofigumbs** [comment]
Initially I considered this a feature of Multi: if I made a GMail app for instance, I would want it to always show GMail regardless of what email links I clicked. Other folks had slightly different workflows, which I was able to accommodate with the `openNewWindowsWith` and `openNewWindowsInBackground` configs. If you're still using Multi, I'd love to hear a bit more about your setup and how you distinguish "an app" and "the browser" in your workflow. I think dynamic tabs functionality would be a big lift (relative to how simple Multi currently is), so I'd be interested to see if there's a simpler solution that would work for you.

**Comment by vanyauhalin** [comment]
I have to admit that no longer use the Multi — preferred Safari's group tabs.

At work, they constantly send me links in the messenger to various repositories, resources, and it’s easier for me to open them right away in a browser. I tried to separate work resources from personal with Multi, but it turned out that with group tabs it is easier due to hot keys (`Shift + ⌘ + PageUp/Down`).

Anyway, want to say thank you for your app — I liked the whole idea of separation of responsibility. Think we can close this issue.
