### ISSUE TITLE
Backspace button works as browser Back in edit field

### ISSUE THREAD

**Issue by alkalim** [kofigumbs/multi#81]
Hi, thanks for the great app! 

I've noticed one issue. Created Evernote web app, but when I edit a note and press backspace it takes me back in browsing history instead of deleting a character in the edit area. Is there any work around?

**Comment by kofigumbs** [comment]
Yes, you can work around this with [Custom JS](https://github.com/kofigumbs/multi#custom-jscss). Here's a script that disables the Backspace browser functionality:

```js
document.addEventListener('keydown', event => {
  if (event.key === 'Backspace' && event.target.nodeName.toLowerCase() === 'body')
    event.preventDefault();
})
```
