### ISSUE TITLE
BigInt64Array is undefined

### ISSUE THREAD

**Issue by bugwheels94** [kofigumbs/multi#83]
I have Safari 14 and Safari 15. Both support BigInt64Array. Then how come this is not supporting it is using same webkit view.

Because of the error. code-server which is vscode in browser is not running in multi which would be amazing

**Comment by bugwheels94** [comment]
zoom is also active very weirdly. zoom is setting css zoom on body and not safari native

**Comment by kofigumbs** [comment]
> I have Safari 14 and Safari 15. Both support BigInt64Array. Then how come this is not supporting it is using same webkit view.

I don't think Safari uses the same webkit view. Multi uses the webkit version that is installed with your OS, but I Safari packages its own copy of webkit for stability purposes. I tested on my machine and `BigInt64Array` is defined in my Multi apps. Maybe you have a pending OS upgrade?

> zoom is also active very weirdly. zoom is setting css zoom on body and not safari native

Yes, zoom is currently implemented as a CSS update. There's not really a such thing as "safari native" zoom. The closest concept would probably be `WKWebView.magnification`, but the behavior is a little different. This question and the top answer explain the difference pretty well: https://stackoverflow.com/questions/50279294/wkwebview-content-not-fitting-after-magnification

**Comment by bugwheels94** [comment]
@kofigumbs You know this stuff better than me. I am attaching the video for your reference hence because I feel like I could not explain myself well

https://user-images.githubusercontent.com/4629859/172109120-7a9aefd9-df31-433d-95a4-890634bb824a.mov
