### ISSUE TITLE
Cannot create app because Null doesn't have permission to access Documents from Terminal

### ISSUE THREAD

**Issue by dantnad** [kofigumbs/multi#85]
Hello there!

I'm currently trying to create apps but I get an error saying the following:
![Captura de pantalla 2022-07-22 a la(s) 16 42 25](https://user-images.githubusercontent.com/39326187/180572564-dc9aa9f0-97b0-4408-ae40-b7a27b07cb31.png)

Sorry, my main language is Spanish. I've tried giving full disk access to both Terminal and Multi app but this won't work, apparently because each time you try to create an app a new temporary folder containing a fresh copy of create-mac-app is created and that copy is not authorized.

Workaround: open the folder an execute the create-mac-app executable from there, then the app is created with the configuration you were specifying.

MacOS version: MacOS Ventura 13.0 Beta build 22A5286j

**Comment by yogeshvar** [comment]
+1

**Comment by kofigumbs** [comment]
Sorry folks, I'm not running the macOS Ventura Preview, and I have no plans to. I haven't been able to reproduce this on Montery, so I don't imagine I'll be much help unless this issue continues into the wider release of the OS. I'd love to accept a contribution here if anyone's able to get to the bottom of it.
