### ISSUE TITLE
No banner notifications, only alert.

### ISSUE THREAD

**Issue by Woet** [kofigumbs/multi#86]
I saw https://github.com/kofigumbs/multi/issues/39 but since it's been closed for nearly 2 years, I thought a new issue would be better.

I'm using web.whatsapp.com using Multi 2.2.0 and while I always hear the new message sound, I don't get the notification itself using the default banner notifications. If I change it to alert instead of banner, they do show up. As soon as I go back to banner, they stop showing up.

**Message sound but no visible notification:**

<img width="350" alt="Screenshot 2022-07-27 at 13 20 56" src="https://user-images.githubusercontent.com/3000589/181234887-0b8499f4-fae0-442b-adfd-50a793cbbc19.png">

**Message sound + notification:**

<img width="352" alt="Screenshot 2022-07-27 at 13 20 58" src="https://user-images.githubusercontent.com/3000589/181234882-0d750a4a-fd97-4588-a4c2-0982f65130f6.png">

<img width="370" alt="Screenshot 2022-07-27 at 13 22 00" src="https://user-images.githubusercontent.com/3000589/181235131-7416d976-5284-4f1c-add0-8e24d3c72d55.png">

Not using any do not disturb or focus settings that could cause this.

**Comment by kofigumbs** [comment]
Could you check whether the `alwaysNotify` [JSON config](https://github.com/kofigumbs/multi#json-configuration) fixes it for you? It sounds like [this issue](https://stackoverflow.com/a/25303802) (by default macOS won't show notifications if the app is visible).

**Comment by fredericocurti** [comment]
Hi, im having the exact same issue.
@kofigumbs tried that and it didn't work

**Comment by Jerry23011** [comment]
Hi, I think Multi is really amazing and easy to setup, would you like to make it localizable so that more users can enjoy the convenience of it?

**Comment by vurtomatic** [comment]
I'm trying to troubleshoot because I'm experiencing the same thing, no notifications from whatsapp.

I tried using alerts and banners, also have `alwaysNotify` set to true.

When I enable "Show in Notification Center", I see a stack of old notifications but not the latest ones when I text myself on whatsapp.
