### ISSUE TITLE
Stack tabs in a vertical sidebar

### ISSUE THREAD

**Issue by timconsidine** [kofigumbs/multi#90]
Just discovered Multi and very excited by the possibilities.
Awesome project.
I notice that tabs for sites in an app are by default horizontal.
Looking in issues history, I see that maybe once they were arranged vertically (e.g. left sidebar).
Is this still possible ? Some parameter when creating the app.
Can't see for looking !

**Comment by kofigumbs** [comment]
Thanks for trying Multi! I actually don’t remember intentionally supporting vertical tabs—do you recall what issue you were looking at? The tab functionality is just the default macOS component, like the one in Finder. So if Finder is capable of showing vertical tabs, I’d think Multi is too.

**Comment by timconsidine** [comment]
Maybe my terminology is wrong, apologies.
I meant tabs arranged like a left sidebar, rather than tabs horizontally across the top.
Kinda like Vivaldi browser has an option to show tabs on the left (or right or bottom).

I'm creating a Multi app which has too many tabs to be displayed horizontally.
So a lot of scrolling and looking.  
Although I get that I can use the Tab menu option to see a vertical list.

I was jumping to a (wrong?) conclusion from https://github.com/kofigumbs/multi/issues/23 that tabs were maybe shown differently before.

If it's not possible, no worries.
Multi is a great app, looking forward to using it.

**Comment by kofigumbs** [comment]
Oh, I think that issue is from before Multi showed tabs at all. Before v2.1.0, tabs were only displayed in the menu bar. You can recreate that aesthetic by hiding the tab bar with `⌘↑T`. 

I did a quick search and didn’t see any way to get native tabs to stack vertically. I think this would have to be implemented with a custom NSView.

**Comment by timconsidine** [comment]
Thanks for looking at it, Kofi.
No worries.

**Comment by kofigumbs** [comment]
Rereading this issue, I think I'm going to close it as "won't fix". Multi right now doesn't have any bespoke interface components, and I think it would be a maintenance burden to add one.
