### ISSUE TITLE
Example apps

### ISSUE THREAD

**Issue by hyperknot** [kofigumbs/multi#92]
Hi, is there any plan of adding a directory of showcase / example apps? I mean for example Slack, etc. 
I'm not thinking anything serious, just an empty folder in the repo where people could add PRs for JSON files they've created / polished over time.

**Comment by kofigumbs** [comment]
Sure, let's give it a try! I just added `Examples/` to the main branch. Would you be interested in submitting a PR?

**Comment by hyperknot** [comment]
Great, added 2 in a PR!
